Gentoo KDE Overlay Metadata has a new mirror
Also update README a little bit.

diff --git a/Documentation/metadata-sync b/Documentation/metadata-sync
--- a/Documentation/metadata-sync
+++ b/Documentation/metadata-sync
@@ -1,12 +1,11 @@
 #!/bin/sh
 
-echo "sorry slackie.soylent.eu is down, somebody else has to provide the metadata"
-exit 255
+METADATA_MIRROR=rsync://gentoo.kynes.de:660/gentoo-metadata-kde/
 
-#if [[ "$(basename $(pwd))" == "Documentation" ]] ; then
-#	echo "Syncing KDE overlay metadata ..."
-#	exec rsync --quiet --recursive --times --compress --delete-delay rsync://slackie.soylent.eu/metadata/kde-testing/ ../metadata/cache/
-#else
-#	echo "ERROR: This script is meant to be run from within Documentation/ !"
-#	exit 255
-#fi
+if [[ "$(basename $(pwd))" == "Documentation" ]] ; then
+	echo "Syncing KDE overlay metadata ..."
+	exec rsync --quiet --recursive --times --compress --delete-delay $METADATA_MIRROR ../metadata/cache/
+else
+	echo "ERROR: This script is meant to be run from within Documentation/ !"
+	exit 255
+fi
